logging:
  level:
    org:
      springframework:
        cloud:
          task: debug
spring:
  batch:
    job:
      jobName: mongo-process
      step-name: slack-process-step
      chunk-size: 5
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: admin